// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8RcM0mikATRdEH8q4_Nytw8bItgo1RKM',
    appId: '1:703489618092:web:1c90a1ed7eb6aa896b2f09',
    messagingSenderId: '703489618092',
    projectId: 'miot-ef69a',
    authDomain: 'miot-ef69a.firebaseapp.com',
    databaseURL: 'https://miot-ef69a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'miot-ef69a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSuI5GqqvTmsqlQaGb0vIxBziHHQjl8BQ',
    appId: '1:703489618092:android:72dd3c16c43855b16b2f09',
    messagingSenderId: '703489618092',
    projectId: 'miot-ef69a',
    databaseURL: 'https://miot-ef69a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'miot-ef69a.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBurzohwTqXBzgHmY0A-Xkpuevjp2w3iw4',
    appId: '1:703489618092:web:ac3aee73ad566af86b2f09',
    messagingSenderId: '703489618092',
    projectId: 'miot-ef69a',
    authDomain: 'miot-ef69a.firebaseapp.com',
    databaseURL: 'https://miot-ef69a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'miot-ef69a.firebasestorage.app',
  );
}
